### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Davyx** [space-nuko/ComfyBox#1]
I'm in ComfyBox directory in Windows 11, I tried "pnpm install" and get an error:  ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In litegraph\packages\core: No matching version found for @litegraph-ts/tsconfig@* inside the workspace

**Comment by space-nuko** [comment]
Try running `pnpm build` inside the litegraph folder first maybe?

It's a separate workspace that's nested, hopefully I can fix it when litegraph-ts/gradio packages are on pnpm

**Comment by Davyx** [comment]
I'm not an engineer so I'm just trying to follow along :) When I tried pnpm build, I got this warning: Local package.json exists, but node_modules missing, did you mean to install? So I tried pnpm install inside the litegraph folder, and that executed successfully.

I tried running pnpm build in litegraph folder after, got different errors this time. It's really long, here's the first part of it:
@litegraph-ts/core:build: vite v4.2.1 building for production...
@litegraph-ts/nodes-basic:build: vite v4.2.1 building for production...
@litegraph-ts/nodes-basic:build: Option "build.lib.name" is required when output formats include "umd" or "iife".
@litegraph-ts/nodes-basic:build: error during build:
@litegraph-ts/nodes-basic:build: Error: Option "build.lib.name" is required when output formats include "umd" or "iife".@litegraph-ts/nodes-basic:build:     at resolveBuildOutputs (file:///D:/StableDiffusion04042023/ComfyBox/litegraph/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:46340:27)
@litegraph-ts/nodes-basic:build:     at build (file:///D:/StableDiffusion04042023/ComfyBox/litegraph/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:46197:25)
@litegraph-ts/nodes-basic:build:     at async CAC.<anonymous> (file:///D:/StableDiffusion04042023/ComfyBox/litegraph/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/cli.js:813:9)
@litegraph-ts/nodes-basic:build:  ELIFECYCLE  Command failed with exit code 1.
@litegraph-ts/core:build: ✓ 0 modules transformed.
@litegraph-ts/core:build: ✓ built in 14ms
@litegraph-ts/core:build: [vite:esbuild] failed to resolve "extends":"tsconfig/base.json" in D:\StableDiffusion04042023\ComfyBox\litegraph\packages\core\tsconfig.json
@litegraph-ts/core:build: file: D:/StableDiffusion04042023/ComfyBox/litegraph/packages/core/src/index.ts
@litegraph-ts/core:build: error during build:
@litegraph-ts/core:build: TSConfckParseError: failed to resolve "extends":"tsconfig/base.json" in D:\StableDiffusion04042023\ComfyBox\litegraph\packages\core\tsconfig.json
@litegraph-ts/core:build:     at resolveExtends (file:///D:/StableDiffusion04042023/ComfyBox/litegraph/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:13299:9)

**Comment by space-nuko** [comment]
Yeah I got the same error on a different machine when I reinstalled, unfortunately I'm away from my dev system for a while so I might not be able to fix it soon

**Comment by space-nuko** [comment]
Could you try it again on latest `master`?

**Comment by space-nuko** [comment]
I'll close this since a lot has been changed since a few weeks ago, but please reopen if you'd like.
