### ISSUE TITLE
Error loading app

### ISSUE THREAD

**Issue by bmaltais** [space-nuko/ComfyBox#124]
When I try to start Comfybox I get this strange error. 

ComfyUI is running on Windows. I can use if just fine at http://127.0.0.1:8188/

When I start Comfybox I get:

![image](https://github.com/space-nuko/ComfyBox/assets/7474674/18df37de-72de-4d16-b1f1-8e99a2a88a74)

and this error show up in the ComfyUI console:

```
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

Any idea what I am doing wrong?

**Comment by Soliver84** [comment]
Start ComfyUI with python main.py --enable-cors-header

this its important:
--enable-cors-header

**Comment by Soliver84** [comment]
HTTPS SSL Error:
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

this Packege:
comfyui-mixlab-nodes
